export const projects = [
  {
    title: "AIRBNB CLONE",
    description: "It's a House Booking Platform.",
    image: "/images/airbnb.png",
    source: "https://github.com/James-Mwendwa/react-airbnb-clone",
    visit: "https://react-airbnb-clone-l681.vercel.app/",
    id: 0,
  },
  {
    title: "JUMIA CLONE",
    description: "It's a House Booking Platform.",
    image: "/images/airbnb.png",
    source: "https://github.com/James-Mwendwa/Jumia-Clone",
    visit: "https://react-airbnb-clone-l681.vercel.app/",
    id: 1,
  },
  {
    title: "DISCORD CLONE",
    description: "It's a House Booking Platform.",
    image: "/images/airbnb.png",
    source: "https://github.com/James-Mwendwa/discord-clone",
    visit: "https://discord-clone-qct9.vercel.app/",
    id: 2,
  },
  {
    title: "WEATHER REPORT APP",
    description: "It's a House Booking Platform.",
    image: "/images/airbnb.png",
    source: "https://github.com/James-Mwendwa/Weather-Report-App",
    visit: "https://react-airbnb-clone-l681.vercel.app/",
    id: 3,
  },
  {
    title: "MOVIE APP",
    description: "It's a House Booking Platform.",
    image: "/images/airbnb.png",
    source: "https://github.com/James-Mwendwa/movie-app",
    visit: "https://movie-app-two-lilac.vercel.app/",
    id: 4,
  },
];
